### ISSUE TITLE
leading zeros in front of real numbers not rejected

### ISSUE THREAD

**Issue by austrin** [DOMjudge/checktestdata#9]
Consider the following script:
```
INT(0, 10, n) SPACE FLOATP(0, 10, 0, 5, x) NEWLINE
```

It rejects the following input:
```
05 5.23
```
But accepts the following input:
```
5 00000000000000000000000005.23
```
(using `FLOAT` instead of `FLOATP` gives the same results).

Is there a rationale for this, or just an oversight?

**Comment by eldering** [comment]
It's "documented" here: https://github.com/DOMjudge/checktestdata/blob/master/libchecktestdata.cc#L970 but arguably an oversight, and indeed would be better to not accept leading zeros, except for a single zero before the decimal point.
